### ISSUE TITLE
Photon is not usable after calling clearcache()

### ISSUE THREAD

**Issue by fida1989** [mrabelwahed/OrangeLabTask#1]
java.lang.IllegalStateException: cache is closed
        at com.jakewharton.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:614)
        at com.jakewharton.disklrucache.DiskLruCache.get(DiskLruCache.java:405)
        at com.imageloadinglib.cache.DiskCache.get(DiskCache.kt:19)
        at com.imageloadinglib.cache.CacheRepository.get(CacheRepository.kt:16)
        at com.imageloadinglib.core.Photon.displayImage(Photon.kt:20)
        at com.vinyassistant.app.activity.HomeActivity$startAdTask$$inlined$fixedRateTimer$1$lambda$1.run(HomeActivity.kt:305)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mrabelwahed** [comment]
can you describe the scenario in details also the device type to be able to solve this issue

**Comment by fida1989** [comment]
I am using Photon as singleton like below declared in Application class:
```
val cacheSize =4194304 //4MiB
imageLoader = Photon.getInstance(context , cacheSize)
```
In the starting activity I am clearing cache like below:
```
MyApplication.imageLoader.clearcache()
```
In the main activity I am using Photon like below where the crash is happening:
```
MyApplication.imageLoader.displayImage(item.getString("image"), ratingImageview, 0)
```
I was testing in regular android emulator.

**Comment by mrabelwahed** [comment]
@fida1989   i  fixed the bug please add the latest dependency of the library "1.0.2"
